CREATE TABLE SUBSCRIBER
(
    SUBSCRIBERID VARCHAR(50) PRIMARY KEY,
    FNAME VARCHAR(50)NOT NULL,
    LNAME VARCHAR(50) NOT NULL,
    PHONE VARCHAR(17) NOT NULL,
    MAIL VARCHAR(50) NOT NULL,
    ISACTIV BOOLEAN NOT NULL DEFAULT TRUE
);