CREATE TABLE SUBSCRIBER
(
    SUBSCRIBERID VARCHAR(256) PRIMARY KEY,
    FNAME VARCHAR(256)NOT NULL,
    LNAME VARCHAR(256) NOT NULL,
    PHONE NUMBER NOT NULL,
    MAIL VARCHAR(256) NOT NULL,
    ISACTIV BOOLEAN NOT NULL DEFAULT TRUE
);