CREATE TABLE SUBSCRIBER
(
    SUBSCRIBERID VARCHAR(256) PRIMARY KEY,
    FNAME VARCHAR(256)NOT NULL,
    LNAME VARCHAR(256) NOT NULL,
    PHONE NUMBER UNIQUE NOT NULL,
    MAIL VARCHAR(256) UNIQUE NOT NULL,
    ISACTIV BOOLEAN NOT NULL DEFAULT TRUE
);